//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_Invoicing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ST_InStock
    {
        public ST_InStock(System.Guid material_guid)
        {
            this.guid = Guid.NewGuid();
            this.count = 0;
            this.material_guid = material_guid;
        }

        public ST_InStock()
        {

        }

        public int serno { get; set; }
        public System.Guid guid { get; set; }
        public System.Guid material_guid { get; set; }

        [Required]
        [Range(0,9999,ErrorMessage = "數量不可小於0")]
        public double count { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public int del_yn { get; set; }

        [ScaffoldColumn(false)]
        public string material_name { get; set; }
    }
}
