//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_Invoicing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ST_Purchase
    {
        public int serno { get; set; }
        public System.Guid guid { get; set; }

        [Display(Name = "採購日期")]
        public System.DateTime purchase_date { get; set; }
        public System.Guid material_guid { get; set; }

        public System.Guid emp_guid { get; set; }

        [Required]
        [Display(Name = "價格")]
        [Range(0, 999999, ErrorMessage = "採購金額限制0~999999")]
        public int purchase_price { get; set; }

        [Required]
        [Display(Name = "標記")]
        public string special_mark { get; set; }

        [Display(Name = "非固定品項名稱")]
        public string special_item { get; set; }

        [Display(Name = "備註")]
        public string remark { get; set; }

        public int finish_yn { get; set; }

        public Nullable<System.DateTime> deleted_at { get; set; }
        public int del_yn { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "採購人員")]
        public string emp_name { get; set; }

        [Required]
        [ScaffoldColumn(false)]
        [Display(Name = "採購項目")]
        public string item_name { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "供應商")]
        public string vendor_name { get; set; }

        [ScaffoldColumn(false)]
        public string font_Color { get; set; }

        public string display_Date { get { return purchase_date.ToString("yyyy-MM-dd") + " " + purchase_date.DayOfWeek; } }
    }
}
