//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_Invoicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Surplus_Month
    {
        public int serno { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime rec_month { get; set; }
        public int expenditure_month { get; set; }
        public int income_month { get; set; }
        public double rice_month { get; set; }
        public double soup_month { get; set; }
        public int month_700 { get; set; }
        public int month_850 { get; set; }
        public int month_meal { get; set; }
        public int personal_month { get; set; }
        public int food_month { get; set; }
        public int supplie_month { get; set; }
        public int other_month { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public int del_yn { get; set; }
    }
}
