//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_Invoicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Vendor
    {
        public int serno { get; set; }
        public System.Guid guid { get; set; }
        public string vendor_name { get; set; }
        public string contact_person { get; set; }
        public string vendor_tel1 { get; set; }
        public string vendor_tel2 { get; set; }
        public string address { get; set; }
        public string uniform_num { get; set; }
        public string payment_mathod { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public int del_yn { get; set; }
    }
}
